// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoApi.Models;

namespace ProyectoApi.Migrations
{
    [DbContext(typeof(MonedaContext))]
    [Migration("20211215122610_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProyectoApi.Models.MonedaItem", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Max")
                        .HasColumnType("real");

                    b.Property<float>("Ultimo")
                        .HasColumnType("real");

                    b.HasKey("Nombre");

                    b.ToTable("MonedaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
